blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models


class Product(models.Model):
    user = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE, 
        related_name='user_products',
        null=True
    )
    photo = models.ImageField(upload_to='media/photo', null=False)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    categories = models.ManyToManyField(
        'Category', 
        related_name='products'
    )

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    user = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE, 
        related_name='user_reviews',
        null=True
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='reviews'
    )
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review for {self.product.name}'

templates/products/create_product.html
{% extends 'layouts/index.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title mb-4">Добавить продукт</h2>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_name" class="form-label">Название продукта:</label>
                            {{ form.name }}
                        </div>
                        <div class="mb-3">
                            <label for="id_description" class="form-label">Описание:</label>
                            {{ form.description }}
                        </div>
                        <div class="mb-3">
                            <label for="id_price" class="form-label">Цена:</label>
                            {{ form.price }}
                        </div>
                        <div class="mb-3">
                            <label for="id_photo" class="form-label">Фото продукта:</label>
                            {{ form.photo }}
                        </div>
                        <div class="mb-3">
                            <label for="id_category" class="form-label">Категория:</label>
                            {{ form.categories   }}
                        </div>
                        <div class="mb-3">
                            <input type="submit" value="Сохранить" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/products/detail_products.html
{% extends 'layouts/index.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>{{ product.name }}</h1>
            <img src="{{ product.photo.url }}" alt="{{ product.name }}" class="img-fluid">
            <p>{{ product.description }}</p>
            <p>Цена: {{ product.price }} С</p>
            <h2>Отзывы:</h2>
            {% if product.reviews.all %}
            <ul>
                {% for review in product.reviews.all %}
                    {% if review.user.profile.avatar %}
                        <img src="{{ review.user.profile.avatar.url }}" class="comment__avatar" width="24">
                    {% else %}
                        <img src="{% static 'avatar.png' %}" class="comment__avatar" width="24">
                    {% endif %}
                    <span class="comment__username text-truncate">{{ review.user.username }}</span>
                    <div style="margin-top: 10px;"></div>

                    <p>{{ review.text }}</p>
                    <p><strong>Дата создания:</strong> {{ review.created_at }}</p>
                {% endfor %}
            </ul>
            {% else %}
            <p>Нет отзывов.</p>
            {% endif %}
            {% if has_change_permission %}
            <a href="/products/{{ product.id }}/edit_product/">
                <button type="submit" class="logout-btn">Обновить</button>
            </a>
            {% endif %}
            <hr>
            {% if user.is_authenticated %}
                <h3>Новый отзыв:</h3>
                <form action="{% url 'review_create' product.id %}" method="post">
                    {% csrf_token %}
                    {{ review_form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            {% endif %}
        </div>
        <div class="col-md-6">
            <h2>Категория:</h2>
            <ul>
                {% if product.categories.all %}
                    {% for category in product.categories.all %}
                    <li>{{ category.name }}</li>
                    {% endfor %}
                {% else %}
                    <li>Нет категории</li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/products/edit_product.html
{% extends 'layouts/index.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title mb-4">Изменить продукт</h2>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_name" class="form-label">Название продукта:</label>
                            {{ form.name }}
                        </div>
                        <div class="mb-3">
                            <label for="id_description" class="form-label">Описание:</label>
                            {{ form.description }}
                        </div>
                        <div class="mb-3">
                            <label for="id_price" class="form-label">Цена:</label>
                            {{ form.price }}
                        </div>
                        <div class="mb-3">
                            <label for="id_photo" class="form-label">Фото продукта:</label>
                            {{ form.photo }}
                        </div>
                        <div class="mb-3">
                            <label for="id_category" class="form-label">Категория:</label>
                            {{ form.categories   }}
                        </div>
                        <div class="mb-3">
                            <input type="submit" value="Сохранить" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/products/products.html
{% extends 'layouts/index.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/products.css' %}">

<div class="container">
    <h1 class="mb-4">Продукты</h1>

    <div class="row mb-4">
        <div class="col-md-6" style="margin-bottom: 15px;">
            <form action="/products/" method="GET" class="form-inline">
                <input type="text" name="search" class="form-control mr-2" placeholder="Поиск" style="margin-bottom: 15px;">

                <button type="submit" class="btn btn-primary">Найти</button>
            </form>
        </div>
        <div class="col-md-6 text-right">
            <div class="btn-group">
                <a href="?sort=price" class="btn btn-secondary">Цена (по возрастанию)</a>
                <a href="?sort=-price" class="btn btn-secondary">Цена (по убыванию)</a>
                <a href="?sort=id" class="btn btn-secondary">Дата добавления (по возрастанию)</a>
                <a href="?sort=-id" class="btn btn-secondary">Дата добавления (по убыванию)</a>
            </div>
        </div>
    </div>

    <div class="row">
        {% for product in products %}
        <div class="col-md-4 mb-4 product-link" onclick="window.location='{% url 'product_detail' product.id %}';">
            <div class="card product-card">
                <img src="/media/{{ product.photo }}" class="card-img-top" alt="Фото продукта">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description|truncatewords:20 }}</p>
                    <p class="card-text price">Цена: {{ product.price }} С</p>
                    <a href="{% url 'product_detail' product.id %}" class="btn btn-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% for page in max_page.paginator.page_range %}
            <li class="page-item{% if page == current_page %} active{% endif %}">
                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
            </li>
            {% endfor %}
        </ul>
    </nav>
</div>

{% endblock %}