blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user import views


urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('verify/', views.verify_view, name='verify'),
    path('profile_update/', views.profile_update_view),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='avatars', default='avatar.png')
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.user.username


class SMSCode(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.code} for user {self.user.username}'
    

user/forms.py
from django import forms

class RegisterForm(forms.Form):
    avatar = forms.ImageField(required=False, label='Фото профиля', widget=forms.FileInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, required=False, label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, required=False, label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}))
    bio = forms.CharField(max_length=500, required=False, label='Биография', widget=forms.Textarea(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, required=True, label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, label='Адрес электронной почты', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Пароль')
    password2 = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Повторите')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        if password != password2:
            raise forms.ValidationError("Пароли не совпадают")
        
        return cleaned_data
    

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, required=True, label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Пароль')


class VerifyForm(forms.Form):
    code = forms.CharField(max_length=10, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))


class ProfileForm(forms.Form):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    bio = forms.CharField(max_length=500, required=False, label='Биография', widget=forms.Textarea(attrs={'class': 'form-control'}))
    avatar = forms.ImageField(required=False, label='Фото профиля', widget=forms.FileInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, required=False, label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, required=False, label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, label='Адрес электронной почты', widget=forms.EmailInput(attrs={'class': 'form-control'}))

user/views.py
import random
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from django.core.mail import send_mail

from user.models import Profile, SMSCode
from user.forms import RegisterForm, LoginForm, VerifyForm, ProfileForm


def register_view(request):
    if request.method == 'GET':
        print(request.user)
        return render(
            request, 
            'user/register.html', 
            {'form': RegisterForm()})
    elif request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            avatar = form.cleaned_data['avatar']
            bio = form.cleaned_data['bio']

            user = User.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                username=username,
                email=email,
                password=password,
                is_active=False
            )

            Profile.objects.create(
                user=user,
                avatar=avatar,
                bio=bio
            )

            code = ''.join([str(random.randint(0, 9)) for _ in range(5)])
            SMSCode.objects.create(
                user=user,
                code=code
            )

            send_mail(
                'Код подтверждения регистрации',
                f'Ваш код подтверждения регистрации: {code}',
                settings.EMAIL_HOST_USER,
                [user.email],
                fail_silently=False
            )
            
            return redirect('verify')
        else:
            return render(request, 'user/register.html', {'form': form})
        

def verify_view(request):
    if request.method == "GET":
        return render(request, 'user/verify.html', {'form': VerifyForm()})
    elif request.method == "POST":
        form = VerifyForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            if SMSCode.objects.filter(code=code).exists():
                sms_code = SMSCode.objects.get(code=code)
                sms_code.user.is_active = True
                sms_code.user.save()
                sms_code.delete()
                return redirect('login')
            else:
                form.add_error(None, 'Неверный код')

    # Рендерим шаблон с формой вне блока else
    return render(request, 'user/verify.html', {'form': form})


def login_view(request):
    if request.method == 'GET':
        return render(request, 'user/login.html', {'form': LoginForm()})
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(**form.cleaned_data) # None or User object
            if user is not None:
                login(request, user)
                return redirect('products_list')
            else:
                form.add_error(None, 'Неправильный логин или пароль')

        return render(request, 'user/login.html', {'form': form})
    

def profile_view(request):
    return render(request, 'user/profile.html')



@login_required
def profile_update_view(request):
    if request.method == 'GET':
        profile = Profile.objects.get(user=request.user)
        form = ProfileForm(
            initial={
                'username': request.user.username,
                'email': request.user.email,
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'avatar': profile.avatar,
                'bio': profile.bio,
            }
        )

        return render(request, 'user/profile_update.html', {'form': form})
    elif request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            request.user.username = form.cleaned_data['username']
            request.user.email = form.cleaned_data['email']
            request.user.first_name = form.cleaned_data['first_name']
            request.user.last_name = form.cleaned_data['last_name']
            request.user.save()

            profile = Profile.objects.get(user=request.user)
            profile.avatar = form.cleaned_data['avatar']
            profile.bio = form.cleaned_data['bio']
            profile.save()

            return redirect('profile')
        else:
            return render(request, 'user/profile_update.html', {'form': form})
        

def logout_view(request):
    logout(request)
    return redirect('login')

templates/user/login.html
{% extends 'layouts/index.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Войти</h2>
                </div>
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group">
                            <label for="{{ form.username.id_for_label }}">Имя пользователя:</label>
                            {{ form.username }}
                            <small class="form-text text-muted"></small>
                            {{ form.username.errors }}
                        </div>
                        <div class="form-group" style="margin-top: 10px;"> <!-- Добавляем вертикальный отступ -->
                            <label for="{{ form.password.id_for_label }}">Пароль:</label>
                            {{ form.password }}
                            <small class="form-text text-muted"></small>
                            {{ form.password.errors }}
                        </div>
                        <div class="form-group" style="margin-top: 10px;"> <!-- Добавляем вертикальный отступ -->
                            <button type="submit" class="btn btn-primary btn-block">Войти</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user/profile.html
<!-- index.html -->
{% extends 'layouts/index.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

<div class="container">
    <div class="row">
        <div class="col-12">
            {% if user.profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" alt="" class="profile-img">
            {% else %}
                <img src="{% static 'avatar.png' %}" alt="" class="profile-img">
            {% endif %}
            <h1>{{ user.first_name }} {{ user.last_name }}</h1>
            <h1>Имя пользователя: {{ user.username }}</h1>
            <p>Адрес электронной почты: {{ user.email }}</p>
            <p>Дата создания: {{ user.date_joined }}</p>
            <form action="/logout/" method="post">
                {% csrf_token %}
                <button type="submit" class="logout-btn">Выйти</button>
            </form>
            
            <div style="margin-top: 10px;"></div>
            
            <a href="/profile_update/">
                <button type="submit" class="logout-btn">Обновить</button>
            </a>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        {% for product in user.user_products.all %}
        <div class="col-md-6">
            <h1>{{ product.name }}</h1>
            <img src="{{ product.photo.url }}" alt="{{ product.name }}" class="img-fluid">
            <p>{{ product.description }}</p>
            <p>Цена: {{ product.price }} С</p>
            <h2>Отзывы:</h2>
            {% if product.reviews.all %}
            <ul>
                {% for review in product.reviews.all %}
                <img src="{{ review.user.profile.avatar.url }}" alt="artyom-akopyan_huyoVKY" class="comment__avatar" width="24">
                <span class="comment__username text-truncate">{{ review.user.username }}</span>
                <p>{{ review.text }}</p>
                <p><strong>Дата создания:</strong> {{ review.created_at }}</p>
                {% endfor %}
            </ul>
            {% else %}
            <p>Нет отзывов.</p>
            {% endif %}
            <a href="/products/{{ product.id }}/edit_product/">
                <button type="submit" class="logout-btn">Обновить</button>
            </a>
            <hr>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/user/profile_update.html
{% extends 'layouts/index.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Изменение профиля</h2>
                </div>
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group" style="margin-bottom: 15px;">
                            <label for="{{ form.avatar.id_for_label }}">Фото профиля:</label>
                            {{ form.avatar }}
                            <small class="form-text text-muted"></small>
                            {{ form.avatar.errors }}
                        </div>
                        <div class="form-group" style="margin-bottom: 15px;">
                            <label for="{{ form.first_name.id_for_label }}">Имя:</label>
                            {{ form.first_name }}
                            <small class="form-text text-muted"></small>
                            {{ form.first_name.errors }}
                        </div>
                        <div class="form-group" style="margin-bottom: 15px;">
                            <label for="{{ form.last_name.id_for_label }}">Фамилия:</label>
                            {{ form.last_name }}
                            <small class="form-text text-muted"></small>
                            {{ form.last_name.errors }}
                        </div>
                        <div class="form-group" style="margin-bottom: 10px;">
                            <label for="{{ form.bio.id_for_label }}">Биография:</label>
                            {{ form.bio }}
                            <small class="form-text text-muted"></small>
                            {{ form.bio.errors }}
                        </div>
                        <div class="form-group" style="margin-bottom: 10px;">
                            <label for="{{ form.username.id_for_label }}">Имя пользователя:</label>
                            {{ form.username }}
                            <small class="form-text text-muted"></small>
                            {{ form.username.errors }}
                        </div>
                        <div class="form-group" style="margin-bottom: 10px;">
                            <label for="{{ form.email.id_for_label }}">Адрес электронной почты:</label>
                            {{ form.email }}
                            <small class="form-text text-muted"></small>
                            {{ form.email.errors }}
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Изменить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user/register.html
{% extends 'layouts/index.html' %}


{% block content %}


<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Регистрация">
</form>

{% endblock %}

templates/user/verify.html
{% extends 'layouts/index.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title mb-4">Verify Code</h2>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_code" class="form-label">Verification Code:</label>
                            {{ form.code }}
                            {% if form.code.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.code.errors }}
                            </div>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <input type="submit" value="Send" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}